# Generated by Django 3.1.11 on 2021-09-01 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='webiste',
            new_name='website',
        ),
    ]
