# Generated by Django 3.1.11 on 2021-09-01 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20210901_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='headshot',
        ),
    ]
